apiVersion: v1
kind: Namespace
metadata:
  name: colis-dev
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: c3m-lptest
  namespace: colis-dev
  labels:
    app: c3m-lptest
spec:
  replicas: 3 #We always want more than 1 replica for HA test
  selector:
    matchLabels:
      app: c3m-lptest
  template:
    metadata:
      labels:
        app: c3m-lptest
    spec:
      volumes:
        - name: template-volume
          persistentVolumeClaim:
            claimName: c3m-grpc-lptpl-pvc
      containers:
        - name: c3m-lptest #1st container
          image: tidusant/c3m-lptest:latest #Dockerhub image
          volumeMounts:
            - mountPath: /app/templates
              name: template-volume
          ports:
            - containerPort: 8082 #Exposes the port 8901 of the container
          env:
            - name: ROOTPATH
              value: "/testtpl"
            - name: API_ADD
              value: "http://c3m-api-service:8081"
            - name: LPMIN_ADD
              value: "http://c3mweb-lpmin-service:8090"
---
kind: Service
apiVersion: v1
metadata:
  name: c3m-lptest-service
  namespace: colis-dev
spec:
  type: NodePort
  selector:
    app: c3m-lptest
  ports:
    - name: c3m-lptest-port
      protocol: TCP
      port: 8082
      nodePort: 30082 #must be between 30000 - 32767
