apiVersion: v1
kind: Namespace
metadata:
  name: colis-dev
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: c3m-wapi
  namespace: colis-dev
  labels:
    app: c3m-wapi
spec:
  replicas: 3 #We always want more than 1 replica for HA test
  selector:
    matchLabels:
      app: c3m-wapi
  template:
    metadata:
      labels:
        app: c3m-wapi
    spec:
      containers:
        - name: c3m-wapi #1st container
          image: tidusant/c3m-wapi:latest #Dockerhub image
          ports:
            - containerPort: 8083 #Exposes the port 8901 of the container
          env:
            - name: SESSION_URI
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: devdb_url
            - name: SESSION_DB
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: devdb_name
            - name: AUTH_IP
              value: "c3m-grpc-auth-service:8901"
            - name: SHOP_IP
              value: "c3m-grpc-shop-service:8902"
            - name: ORD_IP
              value: "c3m-grpc-ord-service:8903"
            - name: LPL_IP
                value: "c3m-grpc-lplead-service:8907"
            - name: SESSION_IP
              value: "c3m-grpc-wsession-service:8865"
              #value: "c3m-grpc-ord-service.colis-dev.svc.cluster.local"
---
kind: Service
apiVersion: v1
metadata:
  name: c3m-wapi-service
  namespace: colis-dev
spec:
  type: NodePort
  selector:
    app: c3m-wapi
  ports:
    - name: c3m-wapi-port
      protocol: TCP
      port: 8083
      nodePort: 30083 #must be between 30000 - 32767
