apiVersion: v1
kind: Namespace
metadata:
  name: colis-dev
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: c3m-grpc-page
  namespace: colis-dev
  labels:
    app: c3m-grpc-page
spec:
  replicas: 2 #We always want more than 1 replica for HA
  selector:
    matchLabels:
      app: c3m-grpc-page
  template:
    metadata:
      labels:
        app: c3m-grpc-page
    spec:
      containers:
        - name: c3m-grpc-page #1st container
          image: tidusant/c3m-grpc-page:latest #Dockerhub image
          ports:
            - containerPort: 8904 #Exposes the port 8901 of the container test test
          env:
            - name: CHADMIN_URI
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: devdb_url
            - name: CHADMIN_DB
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: devdb_name

---
kind: Service
apiVersion: v1
metadata:
  name: c3m-grpc-page-service
  namespace: colis-dev
spec:
  type: NodePort
  selector:
    app: c3m-grpc-page
  ports:
    - name: c3m-grpc-page-port
      protocol: TCP
      port: 8904
      nodePort: 30904 #must be between 30000 - 32767
