apiVersion: v1
kind: Namespace
metadata:
  name: colis-dev
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: c3m-grpc-session
  namespace: colis-dev
  labels:
    app: c3m-grpc-session
spec:
  replicas: 2 #We always want more than 1 replica for HA
  selector:
    matchLabels:
      app: c3m-grpc-session
  template:
    metadata:
      labels:
        app: c3m-grpc-session
    spec:
      containers:
        - name: c3m-grpc-session #1st container
          image: tidusant/c3m-grpc-session:latest #Dockerhub image
          ports:
            - containerPort: 8864
          env:
            - name: CHADMIN_URI
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: devdb_url
            - name: CHADMIN_DB
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: devdb_name

---
kind: Service
apiVersion: v1
metadata:
  name: c3m-grpc-session-service
  namespace: colis-dev
spec:
  type: NodePort
  selector:
    app: c3m-grpc-session
  ports:
    - name: c3m-grpc-session-port
      protocol: TCP
      port: 80
      nodePort: 30864 #must be between 30000 - 32767
