apiVersion: v1
kind: Namespace
metadata:
  name: colis-dev
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: c3m-grpc-lptpl-pv
  labels:
    type: local
  annotations:
    pv.beta.kubernetes.io/gid: "1001"
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/c3m/lptemplates"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: c3m-cdn-pv
  labels:
    type: local
  annotations:
    pv.beta.kubernetes.io/gid: "1001"
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/c3m/cdn"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: c3m-grpc-lptpl-pvc
  namespace: colis-dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: c3m-cdn-pvc
  namespace: colis-dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: c3m-grpc-lptpl
  namespace: colis-dev
  labels:
    app: c3m-grpc-lptpl
spec:
  replicas: 3 #We always want more than 1 replica for HA
  selector:
    matchLabels:
      app: c3m-grpc-lptpl
  template:
    metadata:
      labels:
        app: c3m-grpc-lptpl
    spec:
      containers:
        - name: c3m-grpc-lptpl #1st container
          image: tidusant/c3m-grpc-lptpl:latest #Dockerhub image
          volumeMounts:
          - mountPath: /app/templates
            name: template-volume
          - mountPath: /app/cdn
            name: cdn-volume
          ports:
            - containerPort: 8905 #Exposes the port 8901 of the container
          env:
            - name: CHADMIN_URI
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: devdb_url
            - name: CHADMIN_DB
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: devdb_name
      volumes:
      - name: template-volume
        persistentVolumeClaim:
          claimName: c3m-grpc-lptpl-pvc
      - name: cdn-volume
        persistentVolumeClaim:
          claimName: c3m-cdn-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: c3m-grpc-lptpl-service
  namespace: colis-dev
spec:
  type: NodePort
  selector:
    app: c3m-grpc-lptpl
  ports:
    - name: c3m-grpc-lptpl-port
      protocol: TCP
      port: 8905
      nodePort: 30905 #must be between 30000 - 32767
