apiVersion: v1
kind: Namespace
metadata:
  name: colis-dev
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: c3m-grpc-lptpl
  namespace: colis-dev
  labels:
    app: c3m-grpc-lptpl
spec:
  replicas: 2 #We always want more than 1 replica for HA
  selector:
    matchLabels:
      app: c3m-grpc-lptpl
  template:
    metadata:
      labels:
        app: c3m-grpc-lptpl
    spec:
      containers:
        - name: c3m-grpc-lptpl #1st container
          image: tidusant/c3m-grpc-lptpl:latest #Dockerhub image
          volumeMounts:
          - mountPath: /templates
            name: template-volume
          ports:
            - containerPort: 8905 #Exposes the port 8901 of the container test test
          env:
            - name: CHADMIN_URI
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: devdb_url
            - name: CHADMIN_DB
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: devdb_name
      volumes:
      - name: template-volume
        hostPath:
          # directory location on host
          path: ~/c3mdata/templates
          # this field is optional
          type: Directory
---
kind: Service
apiVersion: v1
metadata:
  name: c3m-grpc-lptpl-service
  namespace: colis-dev
spec:
  type: NodePort
  selector:
    app: c3m-grpc-lptpl
  ports:
    - name: c3m-grpc-lptpl-port
      protocol: TCP
      port: 8905
      nodePort: 30905 #must be between 30000 - 32767
