apiVersion: v1
kind: Namespace
metadata:
  name: colis-dev
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: c3mdev-lptpl-pv
  labels:
    type: local
  annotations:
    pv.beta.kubernetes.io/gid: "1001"
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/c3mdev/lptemplates"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: c3mdev-cdn-pv
  labels:
    type: local
  annotations:
    pv.beta.kubernetes.io/gid: "1001"
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/c3mdev/cdn"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: c3mdev-lp-pv
  labels:
    type: local
  annotations:
    pv.beta.kubernetes.io/gid: "1001"
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/c3mdev/lp"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: c3mdev-lptpl-pvc
  namespace: colis-dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: c3mdev-cdn-pvc
  namespace: colis-dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: c3mdev-lp-pvc
  namespace: colis-dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: c3m-api
  namespace: colis-dev
  labels:
    app: c3m-api
spec:
  replicas: 3 #We always want more than 1 replica for HA test
  selector:
    matchLabels:
      app: c3m-api
  template:
    metadata:
      labels:
        app: c3m-api
    spec:
      containers:
        - name: c3m-api #1st container
          image: tidusant/c3m-api:latest #Dockerhub image
          ports:
            - containerPort: 8081 #Exposes the port 8901 of the container
          env:
            - name: SESSION_URI
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: devdb_url
            - name: SESSION_DB
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: devdb_name
            - name: AUTH_IP
              value: "c3m-grpc-auth-service:8901"
            - name: SHOP_IP
              value: "c3m-grpc-shop-service:8902"
            - name: ORD_IP
              value: "c3m-grpc-ord-service:8903"
            - name: PAGE_IP
              value: "c3m-grpc-page-service:8904"
            - name: LPTPL_IP
              value: "c3m-grpc-lptpl-service:8905"
            - name: LP_IP
              value: "c3m-grpc-lp-service:8906"
            - name: SESSION_IP
              value: "c3m-grpc-session-service:8864"
            - name: LPL_IP
              value: "c3m-grpc-lplead-service:8907"
              #value: "c3m-grpc-ord-service.colis-dev.svc.cluster.local"
---
kind: Service
apiVersion: v1
metadata:
  name: c3m-api-service
  namespace: colis-dev
spec:
  type: NodePort
  selector:
    app: c3m-api
  ports:
    - name: c3m-api-port
      protocol: TCP
      port: 8081
      nodePort: 30081 #must be between 30000 - 32767
